DELETE FROM orders;
DELETE FROM wish;
DELETE FROM options;
DELETE FROM product;
DELETE FROM member;
DELETE FROM category;

ALTER TABLE orders ALTER COLUMN id RESTART WITH 1;
ALTER TABLE wish ALTER COLUMN id RESTART WITH 1;
ALTER TABLE options ALTER COLUMN id RESTART WITH 1;
ALTER TABLE product ALTER COLUMN id RESTART WITH 1;
ALTER TABLE member ALTER COLUMN id RESTART WITH 1;
ALTER TABLE category ALTER COLUMN id RESTART WITH 1;
